name: CI
on:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: node scripts/create-everything-list.js
      - run: node scripts/remove-duplicates.js
      - run: node scripts/update-number-of-domains.js
      - run: node scripts/generate-noip.js
      - run: node scripts/generate-dnsmasq.js
      - run: node scripts/generate-adguard.js
      - name: Commit & Push
        uses: actions-x/commit@v6
        with:
          email: noreply@blocklist.site
          name: GitHub Actions
          branch: master
